service: helloworld-scala

provider:
  name: aws
  runtime: java8
  region:

package:
  artifact: target/scala-2.12/hello.jar

functions:
  ErrorHandler:
    handler: hello.ErrorHandler::handleRequest
    events:
      - http:
          path: /error
          method: get
  HelloHandler:
    handler: hello.HelloHandler::handleRequest
    events:
      - http:
          path: /hello
          method: get
  PersonDisjunctionHandler:
    handler: hello.PersonDisjunctionHandler::handleRequest
    events:
      - http:
          path: /persondisjunction
          method: post
  PersonDisjunctionNelHandler:
    handler: hello.PersonDisjunctionNelHandler::handleRequest
    events:
      - http:
          path: /persondisjunctionnel
          method: post
  PersonOptionHandler:
    handler: hello.PersonOptionHandler::handleRequest
    events:
      - http:
          path: /personoption
          method: post
  PersonValidationHandler:
    handler: hello.PersonValidationHandler::handleRequest
    events:
      - http:
          path: /personvalidation
          method: post
  PersonValidationNelHandler:
    handler: hello.PersonValidationNelHandler::handleRequest
    events:
      - http:
          path: /personvalidationnel
          method: post

